var annotated_dup =
[
    [ "DeserializationOption", null, [
      [ "Filter", "classDeserializationOption_1_1Filter.html", null ],
      [ "NestingLimit", "classDeserializationOption_1_1NestingLimit.html", null ]
    ] ],
    [ "detail", null, [
      [ "AllowAllFilter", "structdetail_1_1AllowAllFilter.html", null ],
      [ "ConverterNeedsWriteableRef", "structdetail_1_1ConverterNeedsWriteableRef.html", null ]
    ] ],
    [ "PCA95x5", null, [
      [ "PCA95x5", "classPCA95x5_1_1PCA95x5.html", "classPCA95x5_1_1PCA95x5" ]
    ] ],
    [ "string_traits_impl", null, [
      [ "has_cstr", "structstring__traits__impl_1_1has__cstr.html", null ],
      [ "has_cstr< T, typename enable_if< is_same< decltype(declval< const T >().c_str()), const char * >::value >::type >", "structstring__traits__impl_1_1has__cstr_3_01T_00_01typename_01enable__if_3_01is__same_3_01decltye800fc44f0bcb004059351821a44dc1b.html", null ],
      [ "has_data", "structstring__traits__impl_1_1has__data.html", null ],
      [ "has_data< T, typename enable_if< is_same< decltype(declval< const T >().data()), const char * >::value >::type >", "structstring__traits__impl_1_1has__data_3_01T_00_01typename_01enable__if_3_01is__same_3_01declty5d9e3ccac430f1fc9f65678747ade433.html", null ],
      [ "has_length", "structstring__traits__impl_1_1has__length.html", null ],
      [ "has_length< T, typename enable_if< is_same< decltype(declval< const T >().length()), size_t >::value >::type >", "structstring__traits__impl_1_1has__length_3_01T_00_01typename_01enable__if_3_01is__same_3_01declf921f5201eb8213c79cd96d5a4ba77db.html", null ],
      [ "has_size", "structstring__traits__impl_1_1has__size.html", null ],
      [ "has_size< T, typename enable_if< is_same< decltype(declval< const T >().size()), size_t >::value >::type >", "structstring__traits__impl_1_1has__size_3_01T_00_01typename_01enable__if_3_01is__same_3_01declty37f3f8f8beadde1128e78725aeb45c8f.html", null ]
    ] ],
    [ "StringStoragePolicy", null, [
      [ "Copy", "structStringStoragePolicy_1_1Copy.html", null ],
      [ "Link", "structStringStoragePolicy_1_1Link.html", null ],
      [ "LinkOrCopy", "structStringStoragePolicy_1_1LinkOrCopy.html", null ]
    ] ],
    [ "Utf16", null, [
      [ "Codepoint", "classUtf16_1_1Codepoint.html", null ]
    ] ],
    [ "Adafruit_ADS1015", "classAdafruit__ADS1015.html", "classAdafruit__ADS1015" ],
    [ "Adafruit_ADS1115", "classAdafruit__ADS1115.html", "classAdafruit__ADS1115" ],
    [ "Adafruit_ADS1X15", "classAdafruit__ADS1X15.html", "classAdafruit__ADS1X15" ],
    [ "Adafruit_BMP3XX", "classAdafruit__BMP3XX.html", "classAdafruit__BMP3XX" ],
    [ "Adafruit_BusIO_Register", "classAdafruit__BusIO__Register.html", "classAdafruit__BusIO__Register" ],
    [ "Adafruit_BusIO_RegisterBits", "classAdafruit__BusIO__RegisterBits.html", "classAdafruit__BusIO__RegisterBits" ],
    [ "Adafruit_I2CDevice", "classAdafruit__I2CDevice.html", "classAdafruit__I2CDevice" ],
    [ "Adafruit_INA219", "classAdafruit__INA219.html", "classAdafruit__INA219" ],
    [ "Adafruit_NeoPixel", "classAdafruit__NeoPixel.html", "classAdafruit__NeoPixel" ],
    [ "Adafruit_SPIDevice", "classAdafruit__SPIDevice.html", "classAdafruit__SPIDevice" ],
    [ "AddPadding", "structAddPadding.html", null ],
    [ "alias_cast_t", "structalias__cast__t.html", null ],
    [ "AllocatorOwner", "classAllocatorOwner.html", null ],
    [ "ArrayComparer", "structArrayComparer.html", null ],
    [ "BasicJsonDocument", "classBasicJsonDocument.html", null ],
    [ "BLESerial", "classBLESerial.html", null ],
    [ "bmp3_adv_settings", "structbmp3__adv__settings.html", "structbmp3__adv__settings" ],
    [ "bmp3_calib_data", "structbmp3__calib__data.html", "structbmp3__calib__data" ],
    [ "bmp3_data", "structbmp3__data.html", "structbmp3__data" ],
    [ "bmp3_dev", "structbmp3__dev.html", "structbmp3__dev" ],
    [ "bmp3_err_status", "structbmp3__err__status.html", "structbmp3__err__status" ],
    [ "bmp3_fifo", "structbmp3__fifo.html", "structbmp3__fifo" ],
    [ "bmp3_fifo_data", "structbmp3__fifo__data.html", "structbmp3__fifo__data" ],
    [ "bmp3_fifo_settings", "structbmp3__fifo__settings.html", "structbmp3__fifo__settings" ],
    [ "bmp3_int_ctrl_settings", "structbmp3__int__ctrl__settings.html", "structbmp3__int__ctrl__settings" ],
    [ "bmp3_int_status", "structbmp3__int__status.html", "structbmp3__int__status" ],
    [ "bmp3_odr_filter_settings", "structbmp3__odr__filter__settings.html", "structbmp3__odr__filter__settings" ],
    [ "bmp3_quantized_calib_data", "structbmp3__quantized__calib__data.html", "structbmp3__quantized__calib__data" ],
    [ "bmp3_reg_calib_data", "structbmp3__reg__calib__data.html", "structbmp3__reg__calib__data" ],
    [ "bmp3_sens_status", "structbmp3__sens__status.html", "structbmp3__sens__status" ],
    [ "bmp3_settings", "structbmp3__settings.html", "structbmp3__settings" ],
    [ "bmp3_status", "structbmp3__status.html", "structbmp3__status" ],
    [ "bmp3_uncomp_data", "structbmp3__uncomp__data.html", "structbmp3__uncomp__data" ],
    [ "BoundedReader", "structBoundedReader.html", null ],
    [ "BoundedReader< const __FlashStringHelper *, void >", "structBoundedReader_3_01const_01____FlashStringHelper_01_5_00_01void_01_4.html", null ],
    [ "BoundedReader< TSource *, typename enable_if< IsCharOrVoid< TSource >::value >::type >", "structBoundedReader_3_01TSource_01_5_00_01typename_01enable__if_3_01IsCharOrVoid_3_01TSource_01_4_1_1value_01_4_1_1type_01_4.html", null ],
    [ "buildInfo", "classbuildInfo.html", null ],
    [ "choose_largest", "structchoose__largest.html", null ],
    [ "CollectionData", "classCollectionData.html", null ],
    [ "Comparer", "structComparer.html", null ],
    [ "Comparer< decltype(nullptr), void >", "structComparer_3_01decltype_07nullptr_08_00_01void_01_4.html", null ],
    [ "Comparer< T, typename enable_if< is_convertible< T, ArduinoJson::JsonVariantConst >::value >::type >", "structComparer_3_01T_00_01typename_01enable__if_3_01is__convertible_3_01T_00_01ArduinoJson_1_1Js9a83c904d88e0c2fa9a99e43ac2747d4.html", null ],
    [ "Comparer< T, typename enable_if< is_integral< T >::value||is_floating_point< T >::value >::type >", "structComparer_3_01T_00_01typename_01enable__if_3_01is__integral_3_01T_01_4_1_1value_7_7is__floa3a92e9d70c77993032caf87b15f2e90f.html", null ],
    [ "Comparer< T, typename enable_if< IsString< T >::value >::type >", "structComparer_3_01T_00_01typename_01enable__if_3_01IsString_3_01T_01_4_1_1value_01_4_1_1type_01_4.html", null ],
    [ "ComparerBase", "structComparerBase.html", null ],
    [ "conditional", "structconditional.html", null ],
    [ "conditional< false, TrueType, FalseType >", "structconditional_3_01false_00_01TrueType_00_01FalseType_01_4.html", null ],
    [ "Converter", "structConverter.html", null ],
    [ "Converter< bool >", "structConverter_3_01bool_01_4.html", null ],
    [ "Converter< const char * >", "structConverter_3_01const_01char_01_5_01_4.html", null ],
    [ "Converter< decltype(nullptr)>", "structConverter_3_01decltype_07nullptr_08_4.html", null ],
    [ "Converter< JsonArray >", "structConverter_3_01JsonArray_01_4.html", null ],
    [ "Converter< JsonArrayConst >", "structConverter_3_01JsonArrayConst_01_4.html", null ],
    [ "Converter< JsonObject >", "structConverter_3_01JsonObject_01_4.html", null ],
    [ "Converter< JsonObjectConst >", "structConverter_3_01JsonObjectConst_01_4.html", null ],
    [ "Converter< JsonString >", "structConverter_3_01JsonString_01_4.html", null ],
    [ "Converter< JsonVariant >", "structConverter_3_01JsonVariant_01_4.html", null ],
    [ "Converter< JsonVariantConst >", "structConverter_3_01JsonVariantConst_01_4.html", null ],
    [ "Converter< SerializedValue< const char * > >", "structConverter_3_01SerializedValue_3_01const_01char_01_5_01_4_01_4.html", null ],
    [ "Converter< SerializedValue< T >, typename detail::enable_if<!detail::is_same< const char *, T >::value >::type >", "structConverter_3_01SerializedValue_3_01T_01_4_00_01typename_01detail_1_1enable__if_3_9detail_1_a5171fe868f6cb4888adad70c627e380.html", null ],
    [ "Converter< T, typename detail::enable_if< detail::is_enum< T >::value >::type >", "structConverter_3_01T_00_01typename_01detail_1_1enable__if_3_01detail_1_1is__enum_3_01T_01_4_1_1value_01_4_1_1type_01_4.html", null ],
    [ "Converter< T, typename detail::enable_if< detail::is_floating_point< T >::value >::type >", "structConverter_3_01T_00_01typename_01detail_1_1enable__if_3_01detail_1_1is__floating__point_3_06090e740ea39ff613b30bad657ed760e.html", null ],
    [ "Converter< T, typename detail::enable_if< detail::is_integral< T >::value &&!detail::is_same< bool, T >::value &&!detail::is_same< char, T >::value >::type >", "structConverter_3_01T_00_01typename_01detail_1_1enable__if_3_01detail_1_1is__integral_3_01T_01_4cac5aae8c7fbe0293de919b177ee3728.html", null ],
    [ "ConverterNeedsWriteableRef", "structConverterNeedsWriteableRef.html", null ],
    [ "CountingDecorator", "classCountingDecorator.html", null ],
    [ "DefaultAllocator", "structDefaultAllocator.html", null ],
    [ "DeserializationError", "classDeserializationError.html", null ],
    [ "DeserializationOptions", "structDeserializationOptions.html", null ],
    [ "DummyWriter", "classDummyWriter.html", null ],
    [ "ElementProxy", "classElementProxy.html", null ],
    [ "enable_if", "structenable__if.html", null ],
    [ "enable_if< true, T >", "structenable__if_3_01true_00_01T_01_4.html", null ],
    [ "EscapeSequence", "classEscapeSequence.html", null ],
    [ "ExternalClIO", "classExternalClIO.html", "classExternalClIO" ],
    [ "ExternalOTAStorage", "classExternalOTAStorage.html", null ],
    [ "first_or_void", "structfirst__or__void.html", null ],
    [ "first_or_void< T, Rest... >", "structfirst__or__void_3_01T_00_01Rest_8_8_8_01_4.html", null ],
    [ "FlashString", "classFlashString.html", null ],
    [ "FloatParts", "structFloatParts.html", null ],
    [ "FloatTraits", "structFloatTraits.html", null ],
    [ "FloatTraits< T, 4 >", "structFloatTraits_3_01T_00_014_01_4.html", null ],
    [ "FloatTraits< T, 8 >", "structFloatTraits_3_01T_00_018_01_4.html", null ],
    [ "HttpClient", "classHttpClient.html", "classHttpClient" ],
    [ "int_t", "structint__t.html", null ],
    [ "int_t< 16 >", "structint__t_3_0116_01_4.html", null ],
    [ "int_t< 32 >", "structint__t_3_0132_01_4.html", null ],
    [ "int_t< 8 >", "structint__t_3_018_01_4.html", null ],
    [ "integral_constant", "structintegral__constant.html", null ],
    [ "InternalStorageESPClass", "classInternalStorageESPClass.html", null ],
    [ "InvalidConversion", "classInvalidConversion.html", null ],
    [ "is_array", "structis__array.html", null ],
    [ "is_array< T[]>", "structis__array_3_01T_0f_0e_4.html", null ],
    [ "is_array< T[N]>", "structis__array_3_01T_0fN_0e_4.html", null ],
    [ "is_base_of", "classis__base__of.html", null ],
    [ "is_class", "structis__class.html", null ],
    [ "is_const", "structis__const.html", null ],
    [ "is_const< const T >", "structis__const_3_01const_01T_01_4.html", null ],
    [ "is_convertible", "structis__convertible.html", null ],
    [ "is_enum", "structis__enum.html", null ],
    [ "is_floating_point", "structis__floating__point.html", null ],
    [ "is_integral", "structis__integral.html", null ],
    [ "is_pointer", "structis__pointer.html", null ],
    [ "is_pointer< T * >", "structis__pointer_3_01T_01_5_01_4.html", null ],
    [ "is_same", "structis__same.html", null ],
    [ "is_same< T, T >", "structis__same_3_01T_00_01T_01_4.html", null ],
    [ "is_signed", "structis__signed.html", null ],
    [ "is_std_string", "structis__std__string.html", null ],
    [ "is_std_string< T, void_t< decltype(T().push_back( 'a')), decltype(T().append(\"\"))> >", "structis__std__string_3_01T_00_01void__t_3_01decltype_07T_07_08_8push__back_07_01_0ja_0j_08_08_0ff6143c37b9436ae6831fd0bf68e91e7.html", null ],
    [ "is_unsigned", "structis__unsigned.html", null ],
    [ "IsChar", "structIsChar.html", null ],
    [ "IsCharOrVoid", "structIsCharOrVoid.html", null ],
    [ "IsCharOrVoid< const T >", "structIsCharOrVoid_3_01const_01T_01_4.html", null ],
    [ "IsString", "structIsString.html", null ],
    [ "IsString< T, typename make_void< typename StringAdapter< T >::AdaptedString >::type >", "structIsString_3_01T_00_01typename_01make__void_3_01typename_01StringAdapter_3_01T_01_4_1_1AdaptedString_01_4_1_1type_01_4.html", null ],
    [ "IsVariant", "structIsVariant.html", null ],
    [ "IteratorReader", "classIteratorReader.html", null ],
    [ "JsonArray", "classJsonArray.html", null ],
    [ "JsonArrayConst", "classJsonArrayConst.html", null ],
    [ "JsonArrayConstIterator", "classJsonArrayConstIterator.html", null ],
    [ "JsonArrayIterator", "classJsonArrayIterator.html", null ],
    [ "JsonDeserializer", "classJsonDeserializer.html", null ],
    [ "JsonDocument", "classJsonDocument.html", null ],
    [ "JsonObject", "classJsonObject.html", null ],
    [ "JsonObjectConst", "classJsonObjectConst.html", null ],
    [ "JsonObjectConstIterator", "classJsonObjectConstIterator.html", null ],
    [ "JsonObjectIterator", "classJsonObjectIterator.html", null ],
    [ "JsonPair", "classJsonPair.html", null ],
    [ "JsonPairConst", "classJsonPairConst.html", null ],
    [ "JsonPairConstPtr", "classJsonPairConstPtr.html", null ],
    [ "JsonPairPtr", "classJsonPairPtr.html", null ],
    [ "JsonSerializer", "classJsonSerializer.html", null ],
    [ "JsonString", "classJsonString.html", null ],
    [ "JsonStringAdapter", "classJsonStringAdapter.html", null ],
    [ "JsonVariant", "classJsonVariant.html", null ],
    [ "JsonVariantConst", "classJsonVariantConst.html", null ],
    [ "Latch", "classLatch.html", null ],
    [ "LightSensor", "classLightSensor.html", "classLightSensor" ],
    [ "Logger", "classLogger.html", null ],
    [ "make_unsigned", "structmake__unsigned.html", null ],
    [ "make_unsigned< char >", "structmake__unsigned_3_01char_01_4.html", null ],
    [ "make_unsigned< signed char >", "structmake__unsigned_3_01signed_01char_01_4.html", null ],
    [ "make_unsigned< signed int >", "structmake__unsigned_3_01signed_01int_01_4.html", null ],
    [ "make_unsigned< signed long >", "structmake__unsigned_3_01signed_01long_01_4.html", null ],
    [ "make_unsigned< signed long long >", "structmake__unsigned_3_01signed_01long_01long_01_4.html", null ],
    [ "make_unsigned< signed short >", "structmake__unsigned_3_01signed_01short_01_4.html", null ],
    [ "make_unsigned< unsigned char >", "structmake__unsigned_3_01unsigned_01char_01_4.html", null ],
    [ "make_unsigned< unsigned int >", "structmake__unsigned_3_01unsigned_01int_01_4.html", null ],
    [ "make_unsigned< unsigned long >", "structmake__unsigned_3_01unsigned_01long_01_4.html", null ],
    [ "make_unsigned< unsigned long long >", "structmake__unsigned_3_01unsigned_01long_01long_01_4.html", null ],
    [ "make_unsigned< unsigned short >", "structmake__unsigned_3_01unsigned_01short_01_4.html", null ],
    [ "make_void", "structmake__void.html", null ],
    [ "MatrixController", "classMatrixController.html", "classMatrixController" ],
    [ "Max", "structMax.html", null ],
    [ "Max< X, Y, false >", "structMax_3_01X_00_01Y_00_01false_01_4.html", null ],
    [ "Max< X, Y, true >", "structMax_3_01X_00_01Y_00_01true_01_4.html", null ],
    [ "MemberProxy", "classMemberProxy.html", null ],
    [ "MemoryManager", "classMemoryManager.html", "classMemoryManager" ],
    [ "MemoryPool", "classMemoryPool.html", null ],
    [ "MqttClient", "classMqttClient.html", "classMqttClient" ],
    [ "MsgPackDeserializer", "classMsgPackDeserializer.html", null ],
    [ "MsgPackSerializer", "classMsgPackSerializer.html", null ],
    [ "NullComparer", "structNullComparer.html", null ],
    [ "numeric_limits", "structnumeric__limits.html", null ],
    [ "numeric_limits< T, typename enable_if< is_integral< T >::value &&is_signed< T >::value >::type >", "structnumeric__limits_3_01T_00_01typename_01enable__if_3_01is__integral_3_01T_01_4_1_1value_01_6ca00500caa32c3c083aef6ce41e00c8c.html", null ],
    [ "numeric_limits< T, typename enable_if< is_unsigned< T >::value >::type >", "structnumeric__limits_3_01T_00_01typename_01enable__if_3_01is__unsigned_3_01T_01_4_1_1value_01_4_1_1type_01_4.html", null ],
    [ "ObjectComparer", "structObjectComparer.html", null ],
    [ "OnConnect", "structOnConnect.html", null ],
    [ "OTAStorage", "classOTAStorage.html", null ],
    [ "OtaUpdate", "classOtaUpdate.html", "classOtaUpdate" ],
    [ "pgm_p", "structpgm__p.html", null ],
    [ "pgm_ptr", "classpgm__ptr.html", null ],
    [ "PowerOverEthernet", "classPowerOverEthernet.html", "classPowerOverEthernet" ],
    [ "PowerSensor", "classPowerSensor.html", null ],
    [ "PrettyJsonSerializer", "classPrettyJsonSerializer.html", null ],
    [ "PubSubClient", "classPubSubClient.html", null ],
    [ "RawComparer", "structRawComparer.html", null ],
    [ "RawData", "structRawData.html", null ],
    [ "Reader", "structReader.html", null ],
    [ "Reader< const __FlashStringHelper *, void >", "structReader_3_01const_01____FlashStringHelper_01_5_00_01void_01_4.html", null ],
    [ "Reader< TSource *, typename enable_if< IsCharOrVoid< TSource >::value >::type >", "structReader_3_01TSource_01_5_00_01typename_01enable__if_3_01IsCharOrVoid_3_01TSource_01_4_1_1value_01_4_1_1type_01_4.html", null ],
    [ "Reader< TSource, typename enable_if< is_base_of< std::istream, TSource >::value >::type >", "structReader_3_01TSource_00_01typename_01enable__if_3_01is__base__of_3_01std_1_1istream_00_01TSo7c2d2ccdaba6a2a85e60d85f94843782.html", null ],
    [ "Reader< TSource, typename enable_if< is_base_of< Stream, TSource >::value >::type >", "structReader_3_01TSource_00_01typename_01enable__if_3_01is__base__of_3_01Stream_00_01TSource_01_4_1_1value_01_4_1_1type_01_4.html", null ],
    [ "Reader< TSource, typename enable_if< is_base_of<::String, TSource >::value >::type >", "structReader_3_01TSource_00_01typename_01enable__if_3_01is__base__of_3_1_1String_00_01TSource_01_4_1_1value_01_4_1_1type_01_4.html", null ],
    [ "Reader< TSource, typename void_< typename TSource::const_iterator >::type >", "structReader_3_01TSource_00_01typename_01void___3_01typename_01TSource_1_1const__iterator_01_4_1_1type_01_4.html", null ],
    [ "Reader< TVariant, typename enable_if< IsVariant< TVariant >::value >::type >", "structReader_3_01TVariant_00_01typename_01enable__if_3_01IsVariant_3_01TVariant_01_4_1_1value_01_4_1_1type_01_4.html", null ],
    [ "remove_const", "structremove__const.html", null ],
    [ "remove_const< const T >", "structremove__const_3_01const_01T_01_4.html", null ],
    [ "remove_cv", "structremove__cv.html", null ],
    [ "remove_cv< const T >", "structremove__cv_3_01const_01T_01_4.html", null ],
    [ "remove_cv< const volatile T >", "structremove__cv_3_01const_01volatile_01T_01_4.html", null ],
    [ "remove_cv< volatile T >", "structremove__cv_3_01volatile_01T_01_4.html", null ],
    [ "remove_reference", "structremove__reference.html", null ],
    [ "remove_reference< T & >", "structremove__reference_3_01T_01_6_01_4.html", null ],
    [ "SerializedValue", "classSerializedValue.html", null ],
    [ "SerializedValue< TChar * >", "classSerializedValue_3_01TChar_01_5_01_4.html", null ],
    [ "SizedRamString", "classSizedRamString.html", null ],
    [ "SizedStringAdapter", "structSizedStringAdapter.html", null ],
    [ "SizedStringAdapter< const __FlashStringHelper *, void >", "structSizedStringAdapter_3_01const_01____FlashStringHelper_01_5_00_01void_01_4.html", null ],
    [ "SizedStringAdapter< TChar *, typename enable_if< IsChar< TChar >::value >::type >", "structSizedStringAdapter_3_01TChar_01_5_00_01typename_01enable__if_3_01IsChar_3_01TChar_01_4_1_1value_01_4_1_1type_01_4.html", null ],
    [ "SlotKeySetter", "structSlotKeySetter.html", null ],
    [ "StaticJsonDocument", "classStaticJsonDocument.html", null ],
    [ "StaticStringAdapter", "classStaticStringAdapter.html", null ],
    [ "StaticStringWriter", "classStaticStringWriter.html", null ],
    [ "StatusLED", "classStatusLED.html", null ],
    [ "string_traits", "structstring__traits.html", null ],
    [ "StringAdapter", "structStringAdapter.html", null ],
    [ "StringAdapter< const __FlashStringHelper *, void >", "structStringAdapter_3_01const_01____FlashStringHelper_01_5_00_01void_01_4.html", null ],
    [ "StringAdapter< const char *, void >", "structStringAdapter_3_01const_01char_01_5_00_01void_01_4.html", null ],
    [ "StringAdapter< JsonString >", "structStringAdapter_3_01JsonString_01_4.html", null ],
    [ "StringAdapter< T, typename enable_if<(string_traits< T >::has_cstr||string_traits< T >::has_data) &&(string_traits< T >::has_length||string_traits< T >::has_size)>::type >", "structStringAdapter_3_01T_00_01typename_01enable__if_3_07string__traits_3_01T_01_4_1_1has__cstr_152d308603e43e361ad3627cec8524ac.html", null ],
    [ "StringAdapter< TChar *, typename enable_if< IsChar< TChar >::value >::type >", "structStringAdapter_3_01TChar_01_5_00_01typename_01enable__if_3_01IsChar_3_01TChar_01_4_1_1value_01_4_1_1type_01_4.html", null ],
    [ "StringAdapter< TChar[N], typename enable_if< IsChar< TChar >::value >::type >", "structStringAdapter_3_01TChar_0fN_0e_00_01typename_01enable__if_3_01IsChar_3_01TChar_01_4_1_1value_01_4_1_1type_01_4.html", null ],
    [ "StringCopier", "classStringCopier.html", null ],
    [ "StringMover", "classStringMover.html", null ],
    [ "TempSensor", "classTempSensor.html", "classTempSensor" ],
    [ "TextFormatter", "classTextFormatter.html", null ],
    [ "type_identity", "structtype__identity.html", null ],
    [ "VariantAttorney", "classVariantAttorney.html", "classVariantAttorney" ],
    [ "VariantComparer", "structVariantComparer.html", null ],
    [ "VariantConstPtr", "classVariantConstPtr.html", null ],
    [ "VariantContent", "unionVariantContent.html", null ],
    [ "VariantData", "classVariantData.html", "classVariantData" ],
    [ "VariantOperators", "structVariantOperators.html", null ],
    [ "VariantOperatorTag", "structVariantOperatorTag.html", null ],
    [ "VariantPtr", "classVariantPtr.html", null ],
    [ "VariantRefBase", "classVariantRefBase.html", null ],
    [ "VariantSlot", "classVariantSlot.html", null ],
    [ "VariantTag", "structVariantTag.html", null ],
    [ "VariantTo", "structVariantTo.html", null ],
    [ "VariantTo< JsonArray >", "structVariantTo_3_01JsonArray_01_4.html", null ],
    [ "VariantTo< JsonObject >", "structVariantTo_3_01JsonObject_01_4.html", null ],
    [ "VariantTo< JsonVariant >", "structVariantTo_3_01JsonVariant_01_4.html", null ],
    [ "Visitor", "structVisitor.html", null ],
    [ "void_", "structvoid__.html", null ],
    [ "Writer", "classWriter.html", null ],
    [ "Writer< TDestination, typename enable_if< is_base_of< std::ostream, TDestination >::value >::type >", "classWriter_3_01TDestination_00_01typename_01enable__if_3_01is__base__of_3_01std_1_1ostream_00_0f8cb29721fd63f4de96f30f352323310.html", null ],
    [ "Writer< TDestination, typename enable_if< is_base_of<::Print, TDestination >::value >::type >", "classWriter_3_01TDestination_00_01typename_01enable__if_3_01is__base__of_3_1_1Print_00_01TDestin48402d0eb837a580bf931bd4074bf0c9.html", null ],
    [ "Writer< TDestination, typename enable_if< is_std_string< TDestination >::value >::type >", "classWriter_3_01TDestination_00_01typename_01enable__if_3_01is__std__string_3_01TDestination_01_4_1_1value_01_4_1_1type_01_4.html", null ],
    [ "Writer<::String, void >", "classWriter_3_1_1String_00_01void_01_4.html", null ],
    [ "ZeroTerminatedRamString", "classZeroTerminatedRamString.html", null ]
];